# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "my-terraform-config-bucket-muna"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "eu-west-2"
  }
}
